2021-10-31 10:32:48,264 INFO    MainThread:664 [wandb_setup.py:_flush():71] setting env: {}
2021-10-31 10:32:48,264 INFO    MainThread:664 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:32:48,264 INFO    MainThread:664 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:32:48,264 INFO    MainThread:664 [wandb_init.py:_log_setup():357] Logging user logs to /home/ubuntu/w251-hw9/master/wandb/run-20211031_103248-pscwd9uw/logs/debug.log
2021-10-31 10:32:48,264 INFO    MainThread:664 [wandb_init.py:_log_setup():358] Logging internal logs to /home/ubuntu/w251-hw9/master/wandb/run-20211031_103248-pscwd9uw/logs/debug-internal.log
2021-10-31 10:32:48,265 INFO    MainThread:664 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fef7b2646d0>
2021-10-31 10:32:48,265 INFO    MainThread:664 [wandb_init.py:init():390] calling init triggers
2021-10-31 10:32:48,265 INFO    MainThread:664 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {}
2021-10-31 10:32:48,265 INFO    MainThread:664 [wandb_init.py:init():435] starting backend
2021-10-31 10:32:48,265 INFO    MainThread:664 [backend.py:_multiprocessing_setup():95] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-31 10:32:48,294 INFO    MainThread:664 [backend.py:ensure_launched():199] starting backend process...
2021-10-31 10:32:48,299 INFO    MainThread:664 [backend.py:ensure_launched():204] started backend process with pid: 698
2021-10-31 10:32:48,300 INFO    MainThread:664 [wandb_init.py:init():444] backend started and connected
2021-10-31 10:32:48,302 INFO    MainThread:664 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-10-31 10:32:48,302 INFO    MainThread:664 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-10-31 10:32:48,302 INFO    MainThread:664 [wandb_init.py:init():503] updated telemetry
2021-10-31 10:32:48,312 INFO    MainThread:664 [wandb_init.py:init():533] communicating current version
2021-10-31 10:32:49,018 INFO    MainThread:664 [wandb_init.py:init():538] got version response 
2021-10-31 10:32:49,018 INFO    MainThread:664 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-10-31 10:32:49,098 INFO    MainThread:664 [wandb_init.py:init():576] starting run threads in backend
2021-10-31 10:32:49,629 INFO    MainThread:664 [wandb_run.py:_console_start():1693] atexit reg
2021-10-31 10:32:49,630 INFO    MainThread:664 [wandb_run.py:_redirect():1567] redirect: SettingsConsole.WRAP
2021-10-31 10:32:49,630 INFO    MainThread:664 [wandb_run.py:_redirect():1604] Wrapping output streams.
2021-10-31 10:32:49,631 INFO    MainThread:664 [wandb_run.py:_redirect():1628] Redirects installed.
2021-10-31 10:32:49,631 INFO    MainThread:664 [wandb_init.py:init():603] run started, returning control to user process
2021-10-31 10:32:49,634 INFO    MainThread:664 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:32:49,634 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:32:52,326 INFO    MainThread:664 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:32:52,329 INFO    MainThread:664 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:32:52,330 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:32:52,809 INFO    MainThread:664 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:32:52,863 INFO    MainThread:664 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:32:52,863 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:32:53,553 INFO    MainThread:664 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:32:53,554 INFO    MainThread:664 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:32:53,554 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:32:54,183 INFO    MainThread:664 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:32:54,184 INFO    MainThread:664 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:32:54,184 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:32:54,916 INFO    MainThread:664 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:32:54,917 INFO    MainThread:664 [wandb_init.py:_pause_backend():270] pausing backend
2021-10-31 10:32:54,917 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:01,248 INFO    MainThread:664 [wandb_init.py:_resume_backend():279] resuming backend
2021-10-31 10:33:01,257 INFO    MainThread:664 [wandb_setup.py:_flush():71] setting env: {}
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_setup.py:_flush():71] setting login settings: {}
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_init.py:_log_setup():357] Logging user logs to /home/ubuntu/w251-hw9/master/wandb/run-20211031_103301-2l0kj1c5/logs/debug.log
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_init.py:_log_setup():358] Logging internal logs to /home/ubuntu/w251-hw9/master/wandb/run-20211031_103301-2l0kj1c5/logs/debug-internal.log
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_init.py:init():390] calling init triggers
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_init.py:init():395] wandb.init called with sweep_config: {}
config: {'epochs': 2, 'batch_size': 500, 'momentum': 0.9, 'WEIGHT_DECAY': 0.0001, 'arch': 'resnet18'}
2021-10-31 10:33:01,258 INFO    MainThread:664 [wandb_init.py:init():410] re-initializing run, found existing run on stack: pscwd9uw
2021-10-31 10:33:01,259 INFO    MainThread:664 [wandb_run.py:finish():1347] finishing run rochelleli/w251-hw9/pscwd9uw
2021-10-31 10:33:01,259 INFO    MainThread:664 [jupyter.py:save_history():429] not saving jupyter history
2021-10-31 10:33:01,259 INFO    MainThread:664 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2021-10-31 10:33:01,259 INFO    MainThread:664 [wandb_init.py:_jupyter_teardown():289] cleaning up jupyter logic
2021-10-31 10:33:01,260 INFO    MainThread:664 [wandb_run.py:_atexit_cleanup():1663] got exitcode: 0
2021-10-31 10:33:01,261 INFO    MainThread:664 [wandb_run.py:_restore():1635] restore
2021-10-31 10:33:01,648 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 783
  total_bytes: 783
}

2021-10-31 10:33:01,766 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 783
  total_bytes: 783
}

2021-10-31 10:33:02,108 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 783
  total_bytes: 5154
}

2021-10-31 10:33:02,210 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}

2021-10-31 10:33:02,310 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}

2021-10-31 10:33:02,411 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}

2021-10-31 10:33:02,512 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}

2021-10-31 10:33:02,613 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}

2021-10-31 10:33:02,754 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}

2021-10-31 10:33:02,955 INFO    MainThread:664 [wandb_run.py:_wait_for_finish():1793] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 5154
  total_bytes: 5154
}
local_info {
}

2021-10-31 10:33:04,059 INFO    MainThread:664 [wandb_run.py:_append_files():2061] logging synced files
